sudo: required

language: bash

services:
- docker

env:
  - DOCKER_IMAGE=maven:3.6-jdk-7-alpine
  - DOCKER_IMAGE=maven:3.6-jdk-8-alpine

install:
  - make docker-install

script:
  - make docker-test
  - make docker-javadoc

after_success:
  - bash <(curl -s https://codecov.io/bash)

cache:
  directories:
    - '$HOME/.m2/repository'
