blank_issues_enabled: false
contact_links:
  - name: Security and Vulnerabilities
    url: https://github.com/OxalisCommunity/vefa-validator/blob/main/SECURITY.md
    about: Please report any security issues or vulnerabilities responsibly to the Oxalis Community team. Please do not use the public issue tracker.
  - name: Questions and Discussions
    url: https://github.com/OxalisCommunity/vefa-validator/discussions/new
    about: Use Github Discussions to ask questions and/or open discussion topics.